server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_wundu
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true

springdoc:
  api-docs:
    path: /docs-wundu
  swagger-ui:
    path: /docs-wundu.html
    enabled: true
  packages-to-scan: ao.com.wundu
  paths-to-match: /api/**