server:
  port: 8080
  #address: 0.0.0.0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wundu-db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true

  hikari:
    initialization-fail-timeout: 60000

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

springdoc:
  api-docs:
    path: /docs-wundu
  swagger-ui:
    path: /docs-wundu.html
    enabled: true
  packages-to-scan: ao.com.wundu
  paths-to-match: /api/**

document:
  storage:
    path: /home/eges-code/Downloads/documents
    user-isolation: true
    allowed-types: application/pdf,image/jpeg,image/jpg,image/png

ocr:
  engine:
    type: huggingface
  huggingface:
    api:
      key: ${HUGGINGFACE_TOKEN}
    model: microsoft/trocr-large-printed
  min:
    confidence:
      rate: 0.85
