server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:postgresql://db:5432/wundu-db
    username: wundu
    password: wundu
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true

  hikari:
    initialization-fail-timeout: 60000

springdoc:
  api-docs:
    path: /docs-wundu
  swagger-ui:
    path: /docs-wundu.html
    enabled: true
  packages-to-scan: ao.com.wundu
  paths-to-match: /api/**
