-- V007 - Alteração da tabela da USERS

ALTER TABLE users ADD COLUMN plan VARCHAR(25) DEFAULT 'Free';
ALTER TABLE users ADD COLUMN plan_start TIMESTAMP;
ALTER TABLE users ADD COLUMN plan_end TIMESTAMP;
ALTER TABLE users ADD COLUMN is_trial BOOLEAN DEFAULT false;